Fix 6

diff --git a/.github/workflows/reconcile.yaml b/.github/workflows/reconcile.yaml
--- a/.github/workflows/reconcile.yaml
+++ b/.github/workflows/reconcile.yaml
@@ -43,4 +43,7 @@ jobs:
         run: |
           for helmrelease in $(flux get helmreleases --all-namespaces | awk 'NR>1 {print $1}'); do
             flux reconcile helmrelease $helmrelease
+            if ! flux reconcile helmrelease $helmrelease; then
+              echo "Failed to process $helmrelease"
+            fi
           done
