Fix 7

diff --git a/.github/workflows/reconcile.yaml b/.github/workflows/reconcile.yaml
--- a/.github/workflows/reconcile.yaml
+++ b/.github/workflows/reconcile.yaml
@@ -39,11 +39,13 @@ jobs:
               flux reconcile kustomization $kustomization
           done
 
-      - name: Reconcile All HelmReleases (if you use Helm)
+      - name: Reconcile All HelmReleases
         run: |
-          for helmrelease in $(flux get helmreleases --all-namespaces | awk 'NR>1 {print $1}'); do
-            flux reconcile helmrelease $helmrelease
-            if ! flux reconcile helmrelease $helmrelease; then
-              echo "Failed to process $helmrelease"
+          for helmrelease in $(flux get helmreleases --all-namespaces | awk 'NR>1 {print $2 "/" $1}'); do
+            namespace=$(echo $helmrelease | cut -f1 -d'/')
+            name=$(echo $helmrelease | cut -f2 -d'/')
+            flux reconcile helmrelease $name --namespace=$namespace
+            if ! flux reconcile helmrelease $name --namespace=$namespace; then
+                echo "Failed to process $name in $namespace"
             fi
           done
